/*
A simple mathematical formula for e is



where n is allowed to go to infinity. This can actually yield very accurate approximations of e using relatively small values of n.
 

Output
Output the approximations of e generated by the above formula for the values of n from 0 to 9. The beginning of your output should appear similar to that shown below.
 

Sample Output
n e
- -----------
0 1
1 2
2 2.5
3 2.666666667
4 2.708333333*/
#include<iostream>
#include<iomanip>
using namespace std;
int f(int x)
{
  if(x==0) return 1;
  if(x==1) return 1;
  else return x*f(x-1);
}
double e(int x)
{
  if(x==0) return 1;
  else return (1.0/(f(x))+(e(x-1)));
}
int main()
{
  cout<<"n"<<" "<<"e"<<endl;
  cout<<"- -----------"<<endl;
  for(int i = 0;i <9 ;i++ )
  {
    if(i<=2)
      cout<<i<<" "<<e(i)<<endl;
    else
      cout<<i<<" "<<fixed<<setprecision(9)<<e(i)<<endl;
  }
}